---
on:
  - push

jobs:
  terraform:
    name: terraform
    env:
      # These variables are used to create an s3 bucket in "aws-s3".
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      # These are variables in the "aws-s3" example.
      TF_VAR_aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
      TF_VAR_aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: "eu-west-1"
      # These are variables in the "azure-blob" example.
      ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
      # These variables are for the terraform vault provider.
      VAULT_ADDR: "http://vault:8200"
      VAULT_TOKEN: "simple"
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        config:
          - name: default
          - name: multiple
          - name: aws-s3
          - name: azure-blob
      max-parallel: 3
    services:
      vault:
        image: hashicorp/vault-enterprise
        env:
          VAULT_DEV_ROOT_TOKEN_ID: "simple"
          VAULT_LICENSE: "${{ secrets.VAULT_LICENSE }}"
        ports:
          - 8200:8200
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: terraform init
        uses: robertdebock/terraform-action@1.1.2
        with:
          directory: ./examples/${{ matrix.config.name }}
      - name: terraform validate
        uses: robertdebock/terraform-action@1.1.2
        with:
          action: validate
          directory: ./examples/${{ matrix.config.name }}
      - name: terraform plan
        uses: robertdebock/terraform-action@1.1.2
        with:
          action: plan
          directory: ./examples/${{ matrix.config.name }}
      # Can't apply; the vault container does not use raft:
      # `* raft storage is not in use`.
      # - name: terraform apply
      #   uses: robertdebock/terraform-action@1.1.2
      #   with:
      #     action: apply
      #     directory: ./examples/${{ matrix.config.name }}
      #   env:
      #     TF_CLI_ARGS: "-input=false -auto-approve"
      # - name: terraform destroy
      #   uses: robertdebock/terraform-action@1.1.2
      #   with:
      #     action: destroy
      #     directory: ./examples/${{ matrix.config.name }}
      #   if: ${{ always() }}
      #   env:
      #     TF_CLI_ARGS: "-input=false -auto-approve"
      - name: check container logs
        run: 'docker logs $(docker ps -aql)'
        if: ${{ failure() }}


