---
on:
  - push

jobs:
  terraform:
    name: terraform
    env:
      # These variables are used to create an s3 bucket in "aws-s3".
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      # These are variables in the "aws-s3" example.
      TF_VAR_aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
      TF_VAR_aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: "eu-west-1"
      # These variables are for the terraform vault provider.
      VAULT_ADDR: "http://vault:8200"
      VAULT_TOKEN: "simple"
      # Untested; use raft.
      VAULT_LOCAL_CONFIG: '{"backend": {"file": {"path": "/vault/file"}}, "default_lease_ttl": "168h", "max_lease_ttl": "720h"}'
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        config:
          - name: default
          - name: multiple
          - name: aws-s3
      max-parallel: 3
    services:
      vault:
        image: hashicorp/vault-enterprise
        env:
          VAULT_DEV_ROOT_TOKEN_ID: "simple"
          VAULT_LICENSE: "${{ secrets.VAULT_LICENSE }}"
        ports:
          - 8200:8200
          - 8201:8201
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: terraform init
        uses: robertdebock/terraform-action@1.1.2
        with:
          directory: ./examples/${{ matrix.config.name }}
      - name: terraform validate
        uses: robertdebock/terraform-action@1.1.2
        with:
          action: validate
          directory: ./examples/${{ matrix.config.name }}
      - name: terraform plan
        uses: robertdebock/terraform-action@1.1.2
        with:
          action: plan
          directory: ./examples/${{ matrix.config.name }}
      - name: terraform apply
        uses: robertdebock/terraform-action@1.1.2
        with:
          action: apply
          directory: ./examples/${{ matrix.config.name }}
        env:
          TF_CLI_ARGS: "-input=false -auto-approve"
      - name: terraform destroy
        uses: robertdebock/terraform-action@1.1.2
        with:
          action: destroy
          directory: ./examples/${{ matrix.config.name }}
        env:
          TF_CLI_ARGS: "-input=false -auto-approve"
        if: ${{ always() }}
